server:
  port: 8000
  error:
    include-stacktrace: never

spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/order_bd
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  application:
    name: order-ms

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka
