server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true